####################################################################################
# Copyright (c) 2023 Thingwala                                                     #
####################################################################################
"""Geyserwala entities."""

from homeassistant.components.binary_sensor import (
    BinarySensorDeviceClass,
)
from homeassistant.components.number import (
    NumberDeviceClass,
)
from homeassistant.components.sensor import (
    SensorDeviceClass,
)
from homeassistant.const import (
    UnitOfTemperature,
)

try:
    from thingwala.geyserwala.const import (
        GEYSERWALA_SETPOINT_TEMP_MAX,
        GEYSERWALA_SETPOINT_TEMP_MIN,
    )
except ModuleNotFoundError:  # pragma: no cover - lets local tests import the module.
    GEYSERWALA_SETPOINT_TEMP_MIN = 30
    GEYSERWALA_SETPOINT_TEMP_MAX = 80

ENTITIES = {
    "binary_sensor": [
        {
            "name": "Pump",
            "key": "pump-status",
            "device_class": BinarySensorDeviceClass.RUNNING,
            "icon_on": "mdi:water-pump",
            "icon_off": "mdi:water-pump-off",
            "visible": False,
        },
        {
            "name": "Element",
            "key": "element-demand",
            "device_class": BinarySensorDeviceClass.POWER,
            "icon_on": "mdi:radiator",
            "icon_off": "mdi:radiator-off",
            "visible": True,
        },
    ],
    "number": [
        {
            "name": "Setpoint",
            "key": "setpoint",
            "device_class": NumberDeviceClass.TEMPERATURE,
            "icon": "mdi:thermostat",
            "visible": True,
            "min": GEYSERWALA_SETPOINT_TEMP_MIN,
            "max": GEYSERWALA_SETPOINT_TEMP_MAX,
            "unit": UnitOfTemperature.CELSIUS,
        },
        {
            "name": "External Setpoint",
            "key": "external-setpoint",
            "device_class": NumberDeviceClass.TEMPERATURE,
            "icon": "mdi:thermostat-auto",
            "visible": True,
            "min": GEYSERWALA_SETPOINT_TEMP_MIN,
            "max": GEYSERWALA_SETPOINT_TEMP_MAX,
            "unit": UnitOfTemperature.CELSIUS,
        },
        {
            "name": "Setpoint Maximum",
            "key": "setpoint-max",
            "device_class": NumberDeviceClass.TEMPERATURE,
            "icon": "mdi:thermostat-high",
            "visible": True,
            "entity_category": "config",
            "min": 30,
            "max": 80,
            "unit": UnitOfTemperature.CELSIUS,
        },
        {
            "name": "Differential",
            "key": "gw-diff",
            "device_class": None,
            "icon": "mdi:delta",
            "visible": True,
            "entity_category": "config",
            "min": 1,
            "max": 30,
            "unit": None,
        },
        {
            "name": "Antifreeze Threshold",
            "key": "gw-antifreeze",
            "device_class": NumberDeviceClass.TEMPERATURE,
            "icon": "mdi:snowflake-thermometer",
            "visible": True,
            "entity_category": "config",
            "min": 0,
            "max": 30,
            "unit": UnitOfTemperature.CELSIUS,
        },
        {
            "name": "DC Maximum Temperature",
            "key": "dc-max-temp",
            "device_class": NumberDeviceClass.TEMPERATURE,
            "icon": "mdi:thermometer-alert",
            "visible": True,
            "entity_category": "config",
            "min": 30,
            "max": 90,
            "unit": UnitOfTemperature.CELSIUS,
        },
        {
            "name": "LDR Minimum",
            "key": "gw-ldr-min",
            "device_class": None,
            "icon": "mdi:brightness-5",
            "visible": True,
            "entity_category": "config",
            "min": 0,
            "max": 1000,
            "unit": None,
        },
        {
            "name": "UTC Offset",
            "key": "utc-offset",
            "device_class": None,
            "icon": "mdi:clock-time-eight-outline",
            "visible": True,
            "entity_category": "config",
            "min": -720,
            "max": 840,
            "unit": None,
        },
        {
            "name": "Port",
            "key": "ntp-port",
            "device_class": None,
            "icon": "mdi:numeric",
            "visible": True,
            "entity_category": "config",
            "min": 1,
            "max": 65535,
            "unit": None,
        },
        {
            "name": "Port",
            "key": "mqtt-port",
            "device_class": None,
            "icon": "mdi:numeric",
            "visible": True,
            "entity_category": "config",
            "min": 1,
            "max": 65535,
            "unit": None,
        },
    ],
    "sensor": [
        {
            "name": "Water Temperature",
            "key": "tank-temp",
            "device_class": SensorDeviceClass.TEMPERATURE,
            "icon": "mdi:thermometer-water",
            "visible": True,
            "unit": UnitOfTemperature.CELSIUS,
        },
        {
            "name": "Collector Temperature",
            "key": "collector-temp",
            "device_class": SensorDeviceClass.TEMPERATURE,
            "icon": "mdi:sun-thermometer",
            "visible": False,
            "unit": UnitOfTemperature.CELSIUS,
        },
    ],
    "switch": [
        {
            "name": "Boost",
            "key": "boost-demand",
            "icon_on": "mdi:fire",
            "icon_off": "mdi:fire-off",
            "visible": True,
        },
        {
            "name": "External Demand",
            "key": "external-demand",
            "icon_on": "mdi:fire",
            "icon_off": "mdi:fire-off",
            "visible": True,
        },
        {
            "name": "External Disable",
            "key": "external-disable",
            "icon_on": "mdi:water-boiler-off",
            "icon_off": "mdi:water-boiler",
            "visible": True,
        },
        {
            "name": "Enabled",
            "key": "app-enable",
            "icon_on": "mdi:application-cog",
            "icon_off": "mdi:application-off",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Enabled",
            "key": "mqtt-enable",
            "icon_on": "mdi:access-point-network",
            "icon_off": "mdi:access-point-network-off",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Auto Update",
            "key": "update-auto",
            "icon_on": "mdi:update",
            "icon_off": "mdi:update-off",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Usage Reporting",
            "key": "usage-reporting",
            "icon_on": "mdi:chart-line",
            "icon_off": "mdi:chart-line-variant",
            "visible": True,
            "entity_category": "config",
        },
    ],
    'text': [
        {
            'name': "Status",
            'key': "status",
            'icon': "mdi:information-outline",
            'visible': True,
        },
        {
            "name": "Configuration",
            "key": "__header_00_configuration",
            "icon": "mdi:format-header-1",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "WiFi",
            "key": "__header_10_wifi",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "SSID",
            "key": "wifi-ssid",
            "icon": "mdi:wifi-cog",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Password",
            "key": "wifi-pass",
            "icon": "mdi:form-textbox-password",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Cloud",
            "key": "__header_20_cloud",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Token",
            "key": "cloud-token",
            "icon": "mdi:cloud-lock",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Device",
            "key": "__header_30_device",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Name",
            "key": "name",
            "icon": "mdi:rename-box",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Hostname",
            "key": "hostname",
            "icon": "mdi:identifier",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Thresholds",
            "key": "__header_40_thresholds",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Local App",
            "key": "__header_50_local_app",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Password",
            "key": "app-pass",
            "icon": "mdi:form-textbox-password",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Time",
            "key": "__header_60_time",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Host",
            "key": "ntp-host",
            "icon": "mdi:server-network",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "MQTT",
            "key": "__header_70_mqtt",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Host",
            "key": "mqtt-host",
            "icon": "mdi:server",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "User",
            "key": "mqtt-user",
            "icon": "mdi:account",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Password",
            "key": "mqtt-pass",
            "icon": "mdi:form-textbox-password",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Topic Template",
            "key": "mqtt-topic-tmpl",
            "icon": "mdi:pound",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Client ID",
            "key": "mqtt-clientid",
            "icon": "mdi:identifier",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Network",
            "key": "__header_80_network",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Static IP",
            "key": "ip-static",
            "icon": "mdi:ip-network",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Netmask",
            "key": "ip-netmask",
            "icon": "mdi:ip-outline",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Gateway",
            "key": "ip-gateway",
            "icon": "mdi:router-network",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "DNS 1",
            "key": "ip-dns1",
            "icon": "mdi:dns",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "DNS 2",
            "key": "ip-dns2",
            "icon": "mdi:dns-outline",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Reporting",
            "key": "__header_90_reporting",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
        {
            "name": "Quality",
            "key": "__header_95_quality",
            "icon": "mdi:format-header-2",
            "visible": True,
            "entity_category": "config",
        },
    ],
}
